_target_: nn_lib.models._Architecture.PatchDiscriminator_monai.PatchDiscriminator
spatial_dims: 2
num_layers_d: 3
num_channels: 64
in_channels: 1
out_channels: 1
kernel_size: 4
norm: "BATCH"
bias: False
padding: 1