working_dir: "/home/deleat/Documents/RomainD/Working_space/"
nn_dir: ${working_dir}NN_models/

path:
    input_path: ${working_dir}Data/Data_LLDM_project/MYOSAIQ/2.-Formated_data/Formated_LGE_processed_128128/

    output_path: ${nn_dir}training_Pytorch/training_ControlNet/training_project_MICCAI_v2/${now:%Y-%m-%d} ${now:%H:%M:%S}


defaults:
  - _self_
  - architecture: ControlNet_arch
  - datamodule: CompressLgeSeg_CNCond_Datamodule
  - dataset: CompressLgeSeg_CNCond_Dataset
  - model: ControlNet
  - processing: processing_CompressLgeSeg



hydra:
  run:
    dir: ${path.output_path}
  
  sweep:
    dir: ${path.output_path}
    subdir: ${hydra.job.num}

  output_subdir: hydra_config

  verbose: [__main__, info]
  

