net:
  shape_data: [1,128,128]
  lat_dims: 32
  lr: 2e-5
  alpha: 2
  beta: 1e-4
  gamma: 0.5
  delta: 20
 
device: cuda
seed: 42


train_params:
  callback:
    monitor: val_loss
    min_delta: 1e-6
    patience: 50

  batch_size: 24
  num_workers: 11
  persistent_workers: True
  split_test: 0.1
  split_val: 0.05
  shuffle: True
  min_epoch: 1
  max_epoch: 2